// GENERIC MODALS
exports.authenticationDialog = require('./authentication-modal');
exports.promptDialog = require('./prompt-modal');
exports.confirmDialog = require('./confirm-modal');
exports.errorMessageDialog = require('./error-message-modal');
exports.warningMessageDialog = require('./warning-message-modal');
// MINIAPPS MODALS
exports.runImportDialog = require('./run-import-modal');
exports.runImportWHDialog = require('./run-import-well-header-modal');
exports.runImportWTDialog = require('./run-import-well-top-modal');
exports.trainModelDialog = require('./train-model-modal');
exports.predictModelDialog = require('./predict-model-modal');
exports.neuralNetWorkPropertiesDialog = require('./neural-network-playground-modal');
