rm -fr ../data-analysis-tab.json
rm -fr ../data-processing-tab.json
rm -fr ../help-tab.json
rm -fr ../petrophysics-tab.json
rm -fr ../project-tab.json
rm -fr ../well-tab.json
rm -fr ../wi-explorer.json
rm -fr ../wi-logplot.json
rm -fr ../source/html/ribbon-block/*-tab
